---
AWSTemplateFormatVersion: "2010-09-09"
Description: ops s3 buckets

Parameters:
  Environment:
    Description: An environment name that will be appended to resource names
    Type: String
    MinLength: 3
    MaxLength: 3
    AllowedValues:
      - ops
    Default: ops

Resources:
  OpsLoggingBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-logs"
      AccessControl: "LogDeliveryWrite"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID:
                Fn::ImportValue: !Sub "wb-cmd-${Environment}-kms-${AWS::Region}-logs-alias"
      LifecycleConfiguration:
        Rules:
          - Id: "Abort Incomplete Multipart Uploads"
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
      Tags:
        - Key: Name
          # wb-cmd-ops-us-west-2-logs
          Value: !Sub "${AWS::StackName}-${AWS::Region}-logs"

  OpsGithubBackUpBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-github-backups"
      AccessControl: "LogDeliveryWrite"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID:
                Fn::ImportValue: !Sub "wb-cmd-${Environment}-kms-${AWS::Region}-github-backups-alias"
      LifecycleConfiguration:
        Rules:
          - Id: "Abort Incomplete Multipart Uploads"
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
      Tags:
        - Key: Name
          # wb-cmd-ops-us-west-2-logs
          Value: !Sub "${AWS::StackName}-${AWS::Region}-github-backups"
  
  OpsGithubBackUpBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
        Bucket: !Ref   OpsGithubBackUpBucket
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS: 
                  - !Sub "arn:aws:iam::${AWS::AccountId}:root"
                  - !Sub "arn:aws:iam::${AWS::AccountId}:user/cmd.ops.jenkins"
              Action: s3:PutObject
              Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-${AWS::Region}-github-backups/*'
              Condition:
                Bool:
                  "aws:SecureTransport": true
            - Effect: Deny
              Principal:
                AWS: "*"
              Action: 
                - "s3:GetObject"
                - "s3:PutObject"
              Resource: !Sub 'arn:aws:s3:::${AWS::StackName}-${AWS::Region}-github-backups/*'
              Condition:
                Bool:
                  "aws:SecureTransport": false
    

Outputs:
  OpsLoggingBucket:
    Description: "ops logging s3 bucket"
    Value: !Ref OpsLoggingBucket
    Export:
      # wb-cmd-ops-s3-us-west-2-logs
      Name: !Sub "${AWS::StackName}-${AWS::Region}-logs"

  OpsGithubBackUpBucket:
    Description: "ops github backups bucket"
    Value: !Ref OpsGithubBackUpBucket
    Export:
      # wb-cmd-ops-s3-us-west-2-github-backups
      Name: !Sub "${AWS::StackName}-${AWS::Region}-github-backups"