---
AWSTemplateFormatVersion: "2010-09-09"

Description: ops jenkins kms keys

Parameters:
  Environment:
    Description: An environment name that will be appended to resource names
    Type: "String"
    MinLength: 3
    MaxLength: 3
    AllowedValues:
      - ops
    Default: ops

Resources:
  OpsLoggingS3KmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: kms key for us-west-2 ops logs, used for all services that log to s3 in us-west-2
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Sub "${AWS::StackName}-${AWS::Region}-logs"
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"
      Tags:
        - Key: "Name"
          # wb-cmd-ops-kms-us-west-2-logs
          Value: !Sub "${AWS::StackName}-${AWS::Region}-logs"

  OpsLoggingS3KmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-${AWS::Region}-logs"
      TargetKeyId: !Ref OpsLoggingS3KmsKey

  OpsGithubBackUpKmsKey:
    Type: "AWS::KMS::Key"
    Properties:
      Description: kms key for malt github backup storage
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Sub "${AWS::StackName}-${AWS::Region}-github-backups"
        Statement:
          - Sid: Allow administration of the key
            Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"
          - Sid: Allow use of this key
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
                - !Sub "arn:aws:iam::${AWS::AccountId}:user/cmd.ops.jenkins"
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
      Tags:
        - Key: "Name"
          # wb-cmd-ops-kms-us-west-2-backups
          Value: !Sub "${AWS::StackName}-${AWS::Region}-github-backups"

  OpsGithubBackUpKmsKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-${AWS::Region}-github-backups"
      TargetKeyId: !Ref OpsGithubBackUpKmsKey

Outputs:
  OpsLoggingS3KmsKeyAlias:
    Description: "ops logging s3 kms alias"
    Value: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${OpsLoggingS3KmsKeyAlias}"
    Export:
      # wb-cmd-ops-kms-us-west-2-logs
      Name: !Sub "${AWS::StackName}-${AWS::Region}-logs-alias"

  OpsGithubBackUpKmsKeyAlias:
    Description: "ops github backups s3 kms alias"
    Value: !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:${OpsGithubBackUpKmsKeyAlias}"
    Export:
      #wb-cmd-ops-us-west-2-backups-alias
      Name: !Sub "${AWS::StackName}-${AWS::Region}-github-backups-alias"
