VpcStack                      : contentnow-vpc
SubProject                    : sandbox-controller
Ec2InstanceType               : r5.xlarge
InstanceCount                 : 1
ProjectName                   : blitline
Environment                   : prod
KeyPairName                   : contentnow-prod
MaxEc2AsgCount                : 2
DesiredEc2Capacity            : 1
SecurityGroupStack            : blitline-prod-sg
ActiveSecurityGroup           : worker-security-group
EBSBlockDeviceName            : "/dev/xvdcz"
EBSVolumeSize                 : 500
EBSVolumeType                 : io1
EBSVolumePIOPS                : 500
Ec2Stack                      : blitline-prod-sandbox-servers
EcrRegion                     : us-west-2
MicroservicesEndpoint         : ms-prod.blitline.warnerbros.com
IamStack                      : blitline-prod-iam
EcrAccount                    : 348180535083
AllqClientImage               : blitline-allq-client
MetricNamePrefix              : blitline-sandbox
AutoscaleMetric               : blitline-sandbox-default-ready
