VpcStack                      : contentnow-vpc-dev
SubProject                    : sandbox-controller
Ec2InstanceType               : r5.xlarge
InstanceCount                 : 1
ProjectName                   : blitline
Environment                   : qa
KeyPairName                   : contentnow-dev
MaxEc2AsgCount                : 2
DesiredEc2Capacity            : 1
SecurityGroupStack            : blitline-qa-sg
ActiveSecurityGroup           : worker-security-group
EBSBlockDeviceName            : "/dev/xvdcz"
EBSVolumeSize                 : 150
EBSVolumeType                 : io1
EBSVolumePIOPS                : 300
Ec2Stack                      : blitline-qa-sandbox-servers
EcrRegion                     : us-west-2
MicroservicesEndpoint         : ms-qa.blitline.warnerbros.com
IamStack                      : blitline-qa-iam
EcrAccount                    : 348180535083
AllqClientImage               : blitline-allq-client
MetricNamePrefix              : blitline-sandbox
AutoscaleMetric               : blitline-sandbox-default-ready
