VpcStack                      : contentnow-vpc
SubProject                    : worker
Ec2InstanceType               : r5.2xlarge
InstanceCount                 : 3
ProjectName                   : blitline
Environment                   : prod
KeyPairName                   : contentnow-prod
MaxEc2AsgCount                : 6
DesiredEc2Capacity            : 3
MinEC2Count                   : 3
SecurityGroupStack            : blitline-prod-sg
ActiveSecurityGroup           : worker-security-group
EBSBlockDeviceName            : "/dev/xvdcz"
EBSVolumeSize                 : 500
EBSVolumeType                 : io1
EBSVolumePIOPS                : 1000
TranscoderId                  : 1571700513045-1x9fya
BlitlineConfigValues          : ewogICAgIkNBQ0hFX1VTRVJOQU1FIjogImVHZno2aGJ6UmZObCIsCiAgICAiQ0FDSEVfUEFTU1dPUkQiOiAiQVZhc2F6WVBFejhLIiwKICAgICJBRVNfS0VZIjogIkora3JPOUFicU1kZVlmNk5rZ1FOcGc9PSIsCiAgICAiQkxJVExJTkVfQUVTX0tFWSI6ICI1MSMzPSVjJGR4eTgsN2E1KysrZVZLNmdUYXRiMiYrJSIsCiAgICAiQVdTX0FDQ0VTU19LRVkiOiAiQUtJQVhNSkMzWTRDN01LUDJSQlkiLAogICAgIkFXU19BQ0NFU1NfU0VDUkVUIjogIjBaVTdoc0dMR1NGbGFaZmRXN2wwMWZFa1RXZHIrV1I2WEhkR2c3RmciLAogICAgIkdPT0dMRV9DTElFTlRfSUQiOiAiIiwKICAgICJHT09HTEVfQ0xJRU5UX1NFQ1JFVCI6ICIiLAogICAgIldBU0FCSV9BQ0NFU1NfS0VZIjogIiIsCiAgICAiV0FTQUJJX0FDQ0VTU19TRUNSRVQiOiAiIiwKICAgICJPVFAiOiAiTm90TmVjZXNzYXJ5Rm9ySGVhZGxlc3MyMDE5IiwKICAgICJKUEVHX01JTklfVVNFUiI6ICJub3VzZXIiLAogICAgIkpQRUdfTUlOSV9VU0VSX1BBU1NXT1JEIjogIm5vcGFzc3dvcmQiLAogICAgIlBST1hZX1VSTCI6ICJodHRwOi8vd3d3Lndhcm5lcmJyb3MuY29tIiwKICAgICJTQ1JZUFQiOiAiVnJxNlZKdmoxbkxNMFEyV2lFbDVnUmVQRURPdnBydmJOem5iUzU2bHV5d1Excmx0ZjhsTXh1enZldXpuNENpRUFOaXdpMUdDYVZIUldZYlhvRnJqVHVHZWFscVJ4MlFNQmM4NVFjOWw2cmVvdjFENHQ4YVlaSURndlBSVW1IIiwKICAgICJUV0VBS0VSIjogImNsYXNzIFR3ZWFrZXJcbiAgICBTRUNSRVQ9J1ZGcS9UeWxZT29CK2E5aFFlZHg9dWNIX25wMTBmOnJnWFJBV3ZzaXQzakpNRDRQSTJtS0w1LUNrN1NVYiBHd1pFejZOOCdcblxuICAgIGRlZiBzZWxmLnR3ZWFrKHZhbCxvZmZzZXQpXG4gICAgICAgIG91dHB1dCA9IFtdXG4gICAgICAgIHZhbC5jaGFycy5lYWNoX3dpdGhfaW5kZXggeyB8YywgaW5kZXh8IG91dHB1dCA8PCBTRUNSRVQuaW5kZXgoYykgKyBvZmZzZXQgKyBpbmRleCAgfVxuICAgICAgICByZXR1cm4gb3V0cHV0LmpvaW4oJywnKVxuICAgIGVuZFxuXG4gICAgZGVmIHNlbGYudW50d2Vhayh2YWwsb2Zmc2V0KVxuICAgICAgICBvdXRwdXQgPSBbXVxuICAgICAgICBpbmRleGVzID0gdmFsLnNwbGl0KCcsJylcbiAgICAgICAgaW5kZXhlcy5lYWNoX3dpdGhfaW5kZXggeyB8aSwgaW5kZXh8IG91dHB1dCA8PCBTRUNSRVRbaS50b19pIC0gb2Zmc2V0IC0gaW5kZXhdIH1cbiAgICAgICAgcmV0dXJuIG91dHB1dC5qb2luKCcnKVxuICAgIGVuZFxuZW5kXG5Ud2Vha2VyXG4iCiAgfQ==
MemcachedAddress              : memcached
DestructLimit                 : '10000'
AllQUrl                       : 'us_queue:8090'
AllQDefaultUrl                : 'us_queue:8090'
CedisPassword                 : jj6GZ
AllQDefaultEUUrl              : 'us_queue:8090'
AllQDefaultUSUrl              : 'us_queue:8090'
BlitlineConfig                : "/u/apps/blitline/current/config/min_blitline_config.json"
Ec2Stack                      : blitline-prod-worker-servers
AlbStack                      : blitline-prod-lb
IamStack                      : blitline-prod-iam
EcrAccount                    : 348180535083
ECSContainerDesiredCount      : 1
EcrRegion                     : us-west-2
MicroservicesEndpoint         : ms-prod.blitline.warnerbros.com
CedisPort                     : 9765
AllQPort                      : 7788
ACurvePublicKey               : Vkx3RyN9cSR9VUpwKGk2NS85RTdVKmlqL3t4cjQ1eyF0UlF5MWtUTwA
TcpClientPort                 : 7768
ACurveServerPublicKey         : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
KinesisRegion                 : us-west-2
LongPollCacheUrl              : http://prod.blitline.warnerbros.com:8080/write
BlitlineBucket                : com-warnerbros-contentnow-prod-rendition-nuxeo
MetricNamePrefix              : blitline-worker
AutoscaleMetric               : blitline-worker-default-ready
DockerTag                     : latest
