VpcStack                      : contentnow-vpc-dev
SubProject                    : worker
Ec2InstanceType               : r5.xlarge
InstanceCount                 : 3
ProjectName                   : blitline
Environment                   : dev
KeyPairName                   : contentnow-dev
MaxEc2AsgCount                : 3
DesiredEc2Capacity            : 3
MinEC2Count                   : 1
SecurityGroupStack            : blitline-dev-sg
ActiveSecurityGroup           : worker-security-group
EBSBlockDeviceName            : "/dev/xvdcz"
EBSVolumeSize                 : 150
EBSVolumeType                 : io1
EBSVolumePIOPS                : 300
TranscoderId                  : 1569617224663-y2zy58
BlitlineConfigValues          : ewogICAgIkNBQ0hFX1VTRVJOQU1FIjogImVHZno2aGJ6UmZObCIsCiAgICAiQ0FDSEVfUEFTU1dPUkQiOiAiQVZhc2F6WVBFejhLIiwKICAgICJBRVNfS0VZIjogIkora3JPOUFicU1kZVlmNk5rZ1FOcGc9PSIsCiAgICAiQkxJVExJTkVfQUVTX0tFWSI6ICI1MSMzPSVjJGR4eTgsN2E1KysrZVZLNmdUYXRiMiYrJSIsCiAgICAiQVdTX0FDQ0VTU19LRVkiOiAiQUtJQVNFUkU1RFEyNEVMTVQ2NDQiLAogICAgIkFXU19BQ0NFU1NfU0VDUkVUIjogIjZDSUovU0xsMERQaE1oVm5FN3hFdHZMU2c1R3VPZCtlelk4MTdwNzgiLAogICAgIkdPT0dMRV9DTElFTlRfSUQiIDogIiIsCiAgICAiR09PR0xFX0NMSUVOVF9TRUNSRVQiIDogIiIsCiAgICAiV0FTQUJJX0FDQ0VTU19LRVkiIDogIiIsCiAgICAiV0FTQUJJX0FDQ0VTU19TRUNSRVQiIDogIiIsCiAgICAiT1RQIiA6ICJOb3ROZWNlc3NhcnlGb3JIZWFkbGVzczIwMTkiLAogICAgIkpQRUdfTUlOSV9VU0VSIiA6ICJub3VzZXIiLAogICAgIkpQRUdfTUlOSV9VU0VSX1BBU1NXT1JEIiA6ICJub3Bhc3N3b3JkIiwKICAgICJQUk9YWV9VUkwiIDogImh0dHA6Ly93d3cud2FybmVyYnJvcy5jb20iLAogICAgIlNDUllQVCIgOiAiVnJxNlZKdmoxbkxNMFEyV2lFbDVnUmVQRURPdnBydmJOem5iUzU2bHV5d1Excmx0ZjhsTXh1enZldXpuNENpRUFOaXdpMUdDYVZIUldZYlhvRnJqVHVHZWFscVJ4MlFNQmM4NVFjOWw2cmVvdjFENHQ4YVlaSURndlBSVW1IIiwKICAgICJUV0VBS0VSIiA6ICJjbGFzcyBUd2Vha2VyXG4gICAgU0VDUkVUPSdWRnEvVHlsWU9vQithOWhRZWR4PXVjSF9ucDEwZjpyZ1hSQVd2c2l0M2pKTUQ0UEkybUtMNS1DazdTVWIgR3daRXo2TjgnXG5cbiAgICBkZWYgc2VsZi50d2Vhayh2YWwsb2Zmc2V0KVxuICAgICAgICBvdXRwdXQgPSBbXVxuICAgICAgICB2YWwuY2hhcnMuZWFjaF93aXRoX2luZGV4IHsgfGMsIGluZGV4fCBvdXRwdXQgPDwgU0VDUkVULmluZGV4KGMpICsgb2Zmc2V0ICsgaW5kZXggIH1cbiAgICAgICAgcmV0dXJuIG91dHB1dC5qb2luKCcsJylcbiAgICBlbmRcblxuICAgIGRlZiBzZWxmLnVudHdlYWsodmFsLG9mZnNldClcbiAgICAgICAgb3V0cHV0ID0gW11cbiAgICAgICAgaW5kZXhlcyA9IHZhbC5zcGxpdCgnLCcpXG4gICAgICAgIGluZGV4ZXMuZWFjaF93aXRoX2luZGV4IHsgfGksIGluZGV4fCBvdXRwdXQgPDwgU0VDUkVUW2kudG9faSAtIG9mZnNldCAtIGluZGV4XSB9XG4gICAgICAgIHJldHVybiBvdXRwdXQuam9pbignJylcbiAgICBlbmRcbmVuZFxuVHdlYWtlclxuIgogIH0KICA=
MemcachedAddress              : memcached
DestructLimit                 : '10000'
AllQUrl                       : 'us_queue:8090'
AllQDefaultUrl                : 'us_queue:8090'
CedisPassword                 : jj6GZ
AllQDefaultEUUrl              : 'us_queue:8090'
AllQDefaultUSUrl              : 'us_queue:8090'
BlitlineConfig                : "/u/apps/blitline/current/config/min_blitline_config.json"
Ec2Stack                      : blitline-dev-worker-servers
AlbStack                      : blitline-dev-lb
IamStack                      : blitline-dev-iam
EcrAccount                    : 348180535083
ECSContainerDesiredCount      : 1
EcrRegion                     : us-west-2
MicroservicesEndpoint         : ms-dev.blitline.warnerbros.com
CedisPort                     : 9765
AllQPort                      : 7788
ACurvePublicKey               : Vkx3RyN9cSR9VUpwKGk2NS85RTdVKmlqL3t4cjQ1eyF0UlF5MWtUTwA
TcpClientPort                 : 7768
ACurveServerPublicKey         : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
KinesisRegion                 : us-west-2
KinesisStreamName             : b_event
LongPollCacheUrl              : http://dev.blitline.warnerbros.com:8080/write
BlitlineBucket                : com-warnerbros-contentnow-dev-emu-nuxeo
MetricNamePrefix              : blitline-worker
AutoscaleMetric               : blitline-worker-default-ready
DockerTag                     : beta


