VpcStack                      : contentnow-vpc-dev
SubProject                    : worker
Ec2InstanceType               : r5.xlarge
InstanceCount                 : 3
ProjectName                   : blitline
Environment                   : qa
KeyPairName                   : contentnow-dev
MaxEc2AsgCount                : 3
DesiredEc2Capacity            : 3
MinEC2Count                   : 2
SecurityGroupStack            : blitline-qa-sg
ActiveSecurityGroup           : worker-security-group
EBSBlockDeviceName            : "/dev/xvdcz"
EBSVolumeSize                 : 150
EBSVolumeType                 : io1
EBSVolumePIOPS                : 300
TranscoderId                  : 1569617224663-y2zy58
BlitlineConfigValues          : ewogICJDQUNIRV9VU0VSTkFNRSI6ICJlR2Z6NmhielJmTmwiLAogICJDQUNIRV9QQVNTV09SRCI6ICJBVmFzYXpZUEV6OEsiLAogICJBRVNfS0VZIjogIkora3JPOUFicU1kZVlmNk5rZ1FOcGc9PSIsCiAgIkJMSVRMSU5FX0FFU19LRVkiOiAiNTEjMz0lYyRkeHk4LDdhNSsrK2VWSzZnVGF0YjImKyUiLAogICJBV1NfQUNDRVNTX0tFWSI6ICJBS0lBU0VSRTVEUTI1VjdUUTZFVCIsCiAgIkFXU19BQ0NFU1NfU0VDUkVUIjogIkdOSlVmR0VNTzFqRjdEU2psL2dzTFZYVElKSG04bmtiWmM1cTF4MysiLAogICJHT09HTEVfQ0xJRU5UX0lEIjogIiIsCiAgIkdPT0dMRV9DTElFTlRfU0VDUkVUIjogIiIsCiAgIldBU0FCSV9BQ0NFU1NfS0VZIjogIiIsCiAgIldBU0FCSV9BQ0NFU1NfU0VDUkVUIjogIiIsCiAgIk9UUCI6ICJOb3ROZWNlc3NhcnlGb3JIZWFkbGVzczIwMTkiLAogICJKUEVHX01JTklfVVNFUiI6ICJub3VzZXIiLAogICJKUEVHX01JTklfVVNFUl9QQVNTV09SRCI6ICJub3Bhc3N3b3JkIiwKICAiUFJPWFlfVVJMIjogImh0dHA6Ly93d3cud2FybmVyYnJvcy5jb20iLAogICJTQ1JZUFQiOiAiVnJxNlZKdmoxbkxNMFEyV2lFbDVnUmVQRURPdnBydmJOem5iUzU2bHV5d1Excmx0ZjhsTXh1enZldXpuNENpRUFOaXdpMUdDYVZIUldZYlhvRnJqVHVHZWFscVJ4MlFNQmM4NVFjOWw2cmVvdjFENHQ4YVlaSURndlBSVW1IIiwKICAiVFdFQUtFUiI6ICJjbGFzcyBUd2Vha2VyXG4gICAgU0VDUkVUPSdWRnEvVHlsWU9vQithOWhRZWR4PXVjSF9ucDEwZjpyZ1hSQVd2c2l0M2pKTUQ0UEkybUtMNS1DazdTVWIgR3daRXo2TjgnXG5cbiAgICBkZWYgc2VsZi50d2Vhayh2YWwsb2Zmc2V0KVxuICAgICAgICBvdXRwdXQgPSBbXVxuICAgICAgICB2YWwuY2hhcnMuZWFjaF93aXRoX2luZGV4IHsgfGMsIGluZGV4fCBvdXRwdXQgPDwgU0VDUkVULmluZGV4KGMpICsgb2Zmc2V0ICsgaW5kZXggIH1cbiAgICAgICAgcmV0dXJuIG91dHB1dC5qb2luKCcsJylcbiAgICBlbmRcblxuICAgIGRlZiBzZWxmLnVudHdlYWsodmFsLG9mZnNldClcbiAgICAgICAgb3V0cHV0ID0gW11cbiAgICAgICAgaW5kZXhlcyA9IHZhbC5zcGxpdCgnLCcpXG4gICAgICAgIGluZGV4ZXMuZWFjaF93aXRoX2luZGV4IHsgfGksIGluZGV4fCBvdXRwdXQgPDwgU0VDUkVUW2kudG9faSAtIG9mZnNldCAtIGluZGV4XSB9XG4gICAgICAgIHJldHVybiBvdXRwdXQuam9pbignJylcbiAgICBlbmRcbmVuZFxuVHdlYWtlclxuIgp9Cg==
MemcachedAddress              : memcached
DestructLimit                 : '10000'
AllQUrl                       : 'us_queue:8090'
AllQDefaultUrl                : 'us_queue:8090'
CedisPassword                 : jj6GZ
AllQDefaultEUUrl              : 'us_queue:8090'
AllQDefaultUSUrl              : 'us_queue:8090'
BlitlineConfig                : "/u/apps/blitline/current/config/min_blitline_config.json"
Ec2Stack                      : blitline-qa-worker-servers
AlbStack                      : blitline-qa-lb
IamStack                      : blitline-qa-iam
EcrAccount                    : 348180535083
ECSContainerDesiredCount      : 1
EcrRegion                     : us-west-2
MicroservicesEndpoint         : ms-qa.blitline.warnerbros.com
CedisPort                     : 9765
AllQPort                      : 7788
ACurvePublicKey               : Vkx3RyN9cSR9VUpwKGk2NS85RTdVKmlqL3t4cjQ1eyF0UlF5MWtUTwA
TcpClientPort                 : 7768
ACurveServerPublicKey         : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
KinesisRegion                 : us-west-2
KinesisStreamName             : b_event
LongPollCacheUrl              : http://qa.blitline.warnerbros.com:8080/write
BlitlineBucket                : com-warnerbros-contentnow-qa-nuxeo
MetricNamePrefix              : blitline-worker
AutoscaleMetric               : blitline-worker-default-ready
DockerTag                     : beta
