pipeline {
    agent {
        label "dind-apline-1cpu-2gb"
    }
    stages{
        stage('start') {
            steps {
                sendNotifications "STARTED"
            }
        }
        stage('build image') {
            steps {
                dir('ops/jenkins/build-agents/alpine/infra-build-tools/jnlp-slave'){
                    script {
                        docker.withRegistry('https://348180535083.dkr.ecr.us-west-2.amazonaws.com', 'ecr:us-west-2:cmdt_jenkins_aws_credentials' ) {
                            docker.build("cmd/jenkins-alpine-jnlp-infra-build-tools-slave:${env.GIT_COMMIT.take(7)}")
                            docker.build("cmd/jenkins-alpine-jnlp-infra-build-tools-slave:latest")
                        }
                    }
                }
            }
        }
        stage('push image') {
            steps {
                dir('ops/jenkins/build-agents/alpine/infra-build-tools/jnlp-slave'){
                    script {
                        docker.withRegistry('https://348180535083.dkr.ecr.us-west-2.amazonaws.com', 'ecr:us-west-2:cmdt_jenkins_aws_credentials') {
                            docker.image("cmd/jenkins-alpine-jnlp-infra-build-tools-slave:${env.GIT_COMMIT.take(7)}").push()
                            docker.image("cmd/jenkins-alpine-jnlp-infra-build-tools-slave:latest").push()
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            sendNotifications currentBuild.currentResult
        }
    }
}