AWSTemplateFormatVersion: "2010-09-09"

Description: "Blitline EC2s for web/microservices/workers"

Parameters:

  Environment:
    Description: An environment name that will be appended to resource names
    Type: String
    AllowedValues:
      - dev
      - qa
      - stg
      - prod
  
  MetricNamePrefix:
    Type: String

  Ec2Stack:
    Type: String

  AutoscaleMetric:
    Type: String

Resources:

  ReadyAlarmHighReadyWorker:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScaleUpPolicyReadyWorker
    Properties:
      AlarmDescription: Scale-up if Ready Jobs >= 15 for 10 minutes
      MetricName: !Sub "${AutoscaleMetric}"
      Namespace: !Sub "Blitline/${Environment}/${MetricNamePrefix}/Allq"
      Statistic: Sum
      Period: "300"
      EvaluationPeriods: "2"
      Threshold: "15"
      Unit: Count
      AlarmActions:
        - Ref: ScaleUpPolicyReadyWorker
      ComparisonOperator: GreaterThanOrEqualToThreshold

  ReadyAlarmLowReadyWorker:
    Type: AWS::CloudWatch::Alarm
    DependsOn:
      - ScaleDownPolicyReadyWorker
    Properties:
      AlarmDescription: Scale-down if Ready Jobs <= 15 for 10 minutes
      MetricName: !Sub "${AutoscaleMetric}"
      Namespace: !Sub "Blitline/${Environment}/${MetricNamePrefix}/Allq"
      Statistic: Sum
      Period: "300"
      EvaluationPeriods: "2"
      Threshold: "15"
      Unit: Count
      AlarmActions:
        - Ref: ScaleDownPolicyReadyWorker
      ComparisonOperator: LessThanOrEqualToThreshold

  ScaleUpPolicyReadyWorker:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Fn::ImportValue: !Sub "${Ec2Stack}-EcsAutoScalingGroup"
      Cooldown: 300
      ScalingAdjustment: "1"

  ScaleDownPolicyReadyWorker:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ChangeInCapacity
      AutoScalingGroupName:
        Fn::ImportValue: !Sub "${Ec2Stack}-EcsAutoScalingGroup"
      Cooldown: 900
      ScalingAdjustment: "-1"
