VpcStack                  : contentnow-vpc-dev
SubProject                : blitline-microservices
Ec2InstanceType           : m5.large
InstanceCount             : "1"
ProjectName               : blitline
Environment               : dev
KeyPairName               : contentnow-dev
MaxEc2AsgCount            : "2"
DesiredEc2Capacity        : "1"
SecurityGroupStack        : blitline-dev-sg
ActiveSecurityGroup       : microservices-security-group
ServiceName               : allq-server
EcrAccount                : "348180535083"
RepoName                  : allq-server
EcrRegion                 : us-west-2
Ec2Stack                  : blitline-dev-ms-servers
CrossAccountTaskRoleArn   : arn:aws:iam::613648124410:role/ecsTaskExecutionRole
EBSBlockDeviceName        : "/dev/xvdcz"
EBSVolumeSize             : "22"
EBSVolumeType             : gp2
EBSVolumePIOPS            : "100"
ServerPort                : "7788"
Serialize                 : "true"
ACurvePublicKey          : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
AuthCode                  : jj6GZ
IamStack                  : blitline-dev-iam
ECSContainerDesiredCount  : 2
AlbStack                  : blitline-dev-lb
KmsStack                  : blitline-dev-kms
FileSystemDns             : fs-92135d38.efs.us-west-2.amazonaws.com
EFSMountLocation          : ~/tmp/allq
EFSSecurityGroup          : efs-security-group

