VpcStack                  : contentnow-vpc
SubProject                : blitline-microservices
Ec2InstanceType           : m5.large
InstanceCount             : "1"
ProjectName               : blitline
Environment               : prod
KeyPairName               : contentnow-prod
MaxEc2AsgCount            : "2"
DesiredEc2Capacity        : "1"
SecurityGroupStack        : blitline-prod-sg
ActiveSecurityGroup       : microservices-security-group
ServiceName               : allq-server
EcrAccount                : "348180535083"
RepoName                  : allq-server
EcrRegion                 : us-west-2
Ec2Stack                  : blitline-prod-ms-servers
EBSBlockDeviceName        : "/dev/xvdcz"
EBSVolumeSize             : "22"
EBSVolumeType             : gp2
EBSVolumePIOPS            : "100"
ServerPort                : "7788"
Serialize                 : "true"
ACurvePublicKey          : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
AuthCode                  : jj6GZ
IamStack                  : blitline-prod-iam
ECSContainerDesiredCount  : 2
AlbStack                  : blitline-prod-lb
KmsStack                  : blitline-prod-kms
EFSSecurityGroup          : efs-security-group
EFSMountLocation          : ~/tmp/allq
FileSystemDns             : fs-5b6435f1.efs.us-west-2.amazonaws.com
