VpcStack                  : contentnow-vpc
SubProject                : blitline-microservices
Ec2InstanceType           : m5.large
InstanceCount             : 1
ProjectName               : blitline
Environment               : stg
KeyPairName               : contentnow-prod
MaxEc2AsgCount            : 2
DesiredEc2Capacity        : 1
SecurityGroupStack        : blitline-stg-sg
ActiveSecurityGroup       : microservices-security-group
ServiceName               : allq-server
EcrAccount                : "348180535083"
RepoName                  : allq-server
EcrRegion                 : us-west-2
Ec2Stack                  : blitline-stg-ms-servers
EBSBlockDeviceName        : "/dev/xvdcz"
EBSVolumeSize             : "22"
EBSVolumeType             : gp2
EBSVolumePIOPS            : "100"
ServerPort                : "7788"
Serialize                 : "true"
ACurvePublicKey          : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
AuthCode                  : jj6GZ
IamStack                  : blitline-stg-iam
ECSContainerDesiredCount  : 2
AlbStack                  : blitline-stg-lb
KmsStack                  : blitline-stg-kms
EFSSecurityGroup          : efs-security-group
FileSystemDns             : fs-f597de5f.efs.us-west-2.amazonaws.com
EFSMountLocation          : ~/tmp/allq
