VpcStack                : contentnow-vpc
SubProject              : blitline-web
Ec2InstanceType         : t3.large
InstanceCount           : 1
ProjectName             : blitline
Environment             : prod
KeyPairName             : contentnow-prod
MaxEc2AsgCount          : 2
DesiredEc2Capacity      : 1
SecurityGroupStack      : blitline-prod-sg
ActiveSecurityGroup     : web-security-group
EcrAccount              : 348180535083
RepoName                : allq-server
EcrRegion               : us-west-2
Ec2Stack                : blitline-prod-web-servers
DebugMode               : "true"
Memory                  : 256
Folder                  : headless
MicroservicesEndpoint   : "ms-prod.blitline.warnerbros.com"
ACurvePublicKey         : Vkx3RyN9cSR9VUpwKGk2NS85RTdVKmlqL3t4cjQ1eyF0UlF5MWtUTwA
ACurveServerPublicKey   : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
TcpClientPort           : 7768
MemoryReservation       : 512
WebImage                : blitline-web
AllqClientImage         : blitline-allq-client
PeripheralsStack        : blitline-prod-peripherals
IamStack                : blitline-prod-iam
EBSBlockDeviceName      : "/dev/xvdcz"
EBSVolumeSize           : 22
EBSVolumeType           : gp2
EBSVolumePIOPS          : 100
AlbStack                : blitline-prod-lb
LongpollingCachePort    : 8080
LongPollCacheUrl        : http://prod.blitline.warnerbros.com:8080/write
DockerTag            : latest
CacheTag                : latest
EFSSecurityGroup        : efs-security-group
EFSMountLocation        : ~/tmp/persisted
FileSystemDns           : fs-056736af.efs.us-west-2.amazonaws.com
