VpcStack                : contentnow-vpc-dev
SubProject              : blitline-web
Ec2InstanceType         : t3.medium
InstanceCount           : 1
ProjectName             : blitline
Environment             : qa
KeyPairName             : contentnow-dev
MaxEc2AsgCount          : 2
DesiredEc2Capacity      : 1
SecurityGroupStack      : blitline-qa-sg
ActiveSecurityGroup     : web-security-group
EcrAccount              : 348180535083
RepoName                : allq-server
EcrRegion               : us-west-2
Ec2Stack                : blitline-qa-web-servers
DebugMode               : "true"
Memory                  : 128
Folder                  : headless
MicroservicesEndpoint   : ms-qa.blitline.warnerbros.com
ACurvePublicKey         : Vkx3RyN9cSR9VUpwKGk2NS85RTdVKmlqL3t4cjQ1eyF0UlF5MWtUTwA
ACurveServerPublicKey   : Y3R4dC1RSnFCQzxBTVVabGk+bHlAJS16d3RAay5Jbng1PU12PndTPwA=
TcpClientPort           : 7768
MemoryReservation       : 256
WebImage                : blitline-web
AllqClientImage         : blitline-allq-client
PeripheralsStack        : blitline-qa-peripherals
IamStack                : blitline-qa-iam
EBSBlockDeviceName      : "/dev/xvdcz"
EBSVolumeSize           : 22
EBSVolumeType           : gp2
EBSVolumePIOPS          : 100
AlbStack                : blitline-qa-lb
LongpollingCachePort    : 8080
LongPollCacheUrl        : http://qa.blitline.warnerbros.com:8080/write
DockerTag            : latest
CacheTag                : latest
EFSSecurityGroup        : efs-security-group
FileSystemDns           : fs-6988c1c3.efs.us-west-2.amazonaws.com
EFSMountLocation        : ~/tmp/persisted
