TempBucket                  : arn:aws:s3:::com-warnerbros-contentnow-dev-emu-rendition-nuxeo
TransientBucket             : arn:aws:s3:::com-warnerbros-contentnow-dev-emu-transient-nuxeo
SourceBucket                : arn:aws:s3:::com-warnerbros-contentnow-dev-emu-nuxeo
LakesideBucket              : arn:aws:s3:::lakeside-dev-s3-us-west-2-nbcu
LakesideBucketKey           : arn:aws:kms:us-west-2:147180035125:key/6c245c66-47e9-4228-8a75-9fac79ee2845
ProjectName                 : blitline
PeripheralsStack            : blitline-dev-peripherals
Environment                 : dev
ShortlifeSuffix             : '-shortlife'
PrivateSuffix               : '-private'

