AWSTemplateFormatVersion: "2010-09-09"

Description: "External vendor access to content now prod live search"

Parameters:
  Environment:
    Description: An environment name that will be appended to resource names
    Type: String
    Default: dev

Resources:
  LiveSearchVendorAssumeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-${AWS::Region}"
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                # Movies anywhere crm account
                - "arn:aws:iam::652788485247:root"
                # Atom
                - "arn:aws:iam::559928269788:root"
                - "arn:aws:iam::866300372279:root"
                # Infosys
                - "arn:aws:iam::183379772110:root"
                # PIC
                - "arn:aws:iam::259237642862:root"
                # Classics
                - "arn:aws:iam::529973818655:root"
                # Dofri
                - "arn:aws:iam::921590218431:root"
                # Dofri Gator Sky
                - "arn:aws:iam::441792793185:root"
                # SVC Gator Sky
                - "arn:aws:iam::077047573990:root"
                # Dalet
                - "arn:aws:iam::559928269788:root"
                # WB Redemption
                - "arn:aws:iam::492664463846:root"
                # EFD - prod publish
                - "arn:aws:iam::077047573990:root"
                # cn-search-pic-integration dev
                - "arn:aws:iam::664186851931:root"
                # cn-search-pic-integration prod
                - "arn:aws:iam::597608033094:root"
              Service:
                - apigateway.amazonaws.com
            Action: ["sts:AssumeRole"]
      Path: /
      ManagedPolicyArns:
        - "arn:aws:iam::507416135429:policy/contentnow-search-clients"
      Tags:
        - Key: Name
          Value: !Sub "${AWS::StackName}-${AWS::Region}"
        - Key: Environment
          Value: !Ref Environment

Outputs:
  LiveSearchVendorAssumeRoleArn:
    Description: contentnow live search assume role arn
    Value: !GetAtt LiveSearchVendorAssumeRole.Arn
    Export:
      # content-now-role-us-west-2-arn
      Name: !Sub "${AWS::StackName}-${AWS::Region}-arn"
