ProjectName                     : blitline
BlitlineTempBucket              : com-warnerbros-contentnow-prod-nuxeo
Environment                     : prod
EncryptionType                  : "sse-s3"
AbortIncompleteMultipartUpload  : true
EncryptionKey                   : ""
DaysAfterInitiation             : 30
LoggingDestinationBucketName    : com-warnerbros-contentnow-prod-accesslogs
LogFilePrefix                   : blitline-prod
AccessControl                   : "Private"
EnableCors                      : true
EnableLoggingBucket             : true
BlockPublicAcls                 : true
BlockPublicPolicy               : true
IgnorePublicAcls                : true
RestrictPublicBuckets           : true
InternalDns                     : "blitline.warnerbros.com."
HostedZone                      : NOTNULL
VpcStack                        : contentnow-vpc
NumberOfStreamShards            : 3
ShortlifeSuffix                 : '-shortlife'
PrivateSuffix                   : '-pvt'
PagerDutyEndpoint               : https://events.pagerduty.com/integration/725b515aef624c8dbaef289db9f209b9/enqueue
