ProjectName                     : blitline
BlitlineTempBucket              : com-warnerbros-contentnow-stg-nuxeo
Environment                     : stg
EncryptionType                  : "sse-s3"
AbortIncompleteMultipartUpload  : true
EncryptionKey                   : ""
DaysAfterInitiation             : 30
LoggingDestinationBucketName    : com-warnerbros-contentnow-prod-accesslogs
LogFilePrefix                   : blitline-stg
AccessControl                   : "Private"
EnableCors                      : true
EnableLoggingBucket             : true
BlockPublicAcls                 : true
BlockPublicPolicy               : true
IgnorePublicAcls                : true
RestrictPublicBuckets           : true
InternalDns                     : "blitline.warnerbros.com."
HostedZone                      : NOTNULL
VpcStack                        : contentnow-vpc
NumberOfStreamShards            : 3
ShortlifeSuffix                 : '-shortlife'
PrivateSuffix                   : '-private'
PagerDutyEndpoint               : https://events.pagerduty.com/integration/b4aa556891254dbeb58ba29a78e977d7/enqueue
