ProjectName                     : blitline
BlitlineTempBucket              : com-warnerbros-contentnow-dev-emu-nuxeo
Environment                     : dev
EncryptionType                  : "sse-s3"
AbortIncompleteMultipartUpload  : true
EncryptionKey                   : ""
DaysAfterInitiation             : 30
LoggingDestinationBucketName    : com-warnerbros-contentnow-dev-accesslogs
LogFilePrefix                   : blitline-dev
AccessControl                   : "Private"
EnableCors                      : true
EnableLoggingBucket             : true
BlockPublicAcls                 : true
BlockPublicPolicy               : true
IgnorePublicAcls                : true
RestrictPublicBuckets           : true
InternalDns                     : "blitline.warnerbros.com."
HostedZone                      : NOTNULL
VpcStack                        : contentnow-vpc-dev
NumberOfStreamShards            : 1
ShortlifeSuffix                 : '-shortlife'
PrivateSuffix                   : '-private'
