AWSTemplateFormatVersion: "2010-09-09"
Description: ops nexus ecr repos

Parameters:
  Environment:
    Description: An environment name that will be appended to resource names
    Type: String
    MinLength: 3
    MaxLength: 3
    AllowedValues:
      - ops
    Default: ops

Resources:
  Nexus:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: "cmd/nexus"
      LifecyclePolicy:
        RegistryId: !Ref AWS::AccountId
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "remove all untagged images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 7
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        - Key: "Name"
          Value: "cmd/nexus"
        - Key: "Name"
          Value: !Ref Environment

Outputs:
  Nexus:
    Description: "ops nexus ecr repo"
    Value: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Nexus}"
    Export:
      Name: !Sub "${AWS::StackName}-cmd-nexus-repo"
