---
AWSTemplateFormatVersion: "2010-09-09"
Description: ops nexus s3 buckets

Parameters:
  Environment:
    Description: An environment name that will be appended to resource names
    Type: String
    MinLength: 3
    MaxLength: 3
    AllowedValues:
      - ops
    Default: ops

Resources:
  NexusConfigs:
    Type: AWS::S3::Bucket
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
    Properties:
      BucketName: !Sub "${AWS::StackName}-repo"
      AccessControl: "Private"
      VersioningConfiguration:
        Status: Enabled
      LoggingConfiguration:
        DestinationBucketName:
          Fn::ImportValue: !Sub "wb-cmd-${Environment}-s3-us-west-2-logs"
        LogFilePrefix: !Sub "${AWS::StackName}-repo"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID:
                Fn::ImportValue: !Sub "wb-cmd-${Environment}-kms-nexus-s3-repo-alias"
      LifecycleConfiguration:
        Rules:
          - Id: "Abort Incomplete Multipart Uploads"
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 30
      Tags:
        - Key: Name
          # wb-cmd-ops-s3-nexus-repo
          Value: !Sub "${AWS::StackName}-repo"
